apiVersion: v1
data:
  common.libsonnet: |
    {
      blobstore: {
        contentAddressableStorage: {
          existenceCaching: {
            existenceCache: {
              cacheSize: 1000 * 1000,
              cacheDuration: '300s',
              cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
            },
            backend: {
              sharding: {
                hashInitialization: 11946695773637837490,
                shards: [
                  {
                    backend: {
                      mirrored: {
                        backendA: { grpc: { address: 'storage-0-0.storage.buildbarn:8981' } },
                        backendB: { grpc: { address: 'storage-0-1.storage.buildbarn:8981' } },
                        replicatorAToB: {
                          remote: { address: 'replicator-0-0-to-0-1.buildbarn:8984' },
                        },
                        replicatorBToA: {
                          remote: { address: 'replicator-0-1-to-0-0.buildbarn:8984' },
                        },
                      },
                    },
                    weight: 1,
                  },
                  {
                    backend: {
                      mirrored: {
                        backendA: { grpc: { address: 'storage-1-0.storage.buildbarn:8981' } },
                        backendB: { grpc: { address: 'storage-1-1.storage.buildbarn:8981' } },
                        replicatorAToB: {
                          remote: { address: 'replicator-1-0-to-1-1.buildbarn:8984' },
                        },
                        replicatorBToA: {
                          remote: { address: 'replicator-1-1-to-1-0.buildbarn:8984' },
                        },
                      },
                    },
                    weight: 1,
                  },
                ],
              },
            },
          },
        },
        actionCache: {
          completenessChecking: {
            backend: {
              sharding: {
                hashInitialization: 14897363947481274433,
                shards: [
                  {
                    backend: {
                      mirrored: {
                        backendA: { grpc: { address: 'storage-0-0.storage.buildbarn:8981' } },
                        backendB: { grpc: { address: 'storage-0-1.storage.buildbarn:8981' } },
                        replicatorAToB: { 'local': {} },
                        replicatorBToA: { 'local': {} },
                      },
                    },
                    weight: 1,
                  },
                  {
                    backend: {
                      mirrored: {
                        backendA: { grpc: { address: 'storage-1-0.storage.buildbarn:8981' } },
                        backendB: { grpc: { address: 'storage-1-1.storage.buildbarn:8981' } },
                        replicatorAToB: { 'local': {} },
                        replicatorBToA: { 'local': {} },
                      },
                    },
                    weight: 1,
                  },
                ],
              },
            },
            maximumTotalTreeSizeBytes: 64 * 1024 * 1024,
          },
        },
      },
      //browserUrl: 'http://bb-browser.example.com:80',
      browserUrl: 'https://bb-browser.%zone%',
      httpListenAddress: ':80',
      maximumMessageSizeBytes: 16 * 1024 * 1024,
      global: {
        diagnosticsHttpServer: {
          listenAddress: ':9980',
          enablePrometheus: true,
          enablePprof: true,
          enableActiveSpans: true,
        },
      },
    }
kind: ConfigMap
metadata:
  name: common
  namespace: buildbarn
