apiVersion: v1
data:
  replicator.jsonnet: |
    local common = import 'common.libsonnet';

    {
      grpcServers: [{
        listenAddresses: [':8984'],
        authenticationPolicy: { allow: {} },
        healthCheckService: 'readiness',
      }],
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      global: common.global,
      source: { grpc: { address: std.extVar("SOURCE") } },
      sink: { grpc: { address: std.extVar("SINK") } },
      replicator: {
        deduplicating: {
          concurrencyLimiting: {
            base: { 'local': {} },
            maximumConcurrency: 100,
          },
        },
      },
    }
kind: ConfigMap
metadata:
  name: replicator
  namespace: buildbarn
