apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage
  namespace: buildbarn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage
  serviceName: storage
  template:
    metadata:
      labels:
        app: storage
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      automountServiceAccountToken: false
      podManagementPolicy: Parallel
      minReadySeconds: 120
      containers:
      - args:
        - /config/storage.jsonnet
        image: ghcr.io/buildbarn/bb-storage:20230629T193729Z-d6a051c
        name: storage
        resources:
          requests:
            cpu: 1000m
            memory: 1Gi
        ports:
        - containerPort: 8981
          protocol: TCP
        - name: metrics
          containerPort: 9980
          protocol: TCP
        volumeMounts:
        - mountPath: /config/
          name: configs
          readOnly: true
        - mountPath: /storage-cas
          name: cas
        - mountPath: /storage-ac
          name: ac
        readinessProbe:
          grpc:
            service: readiness
            port: 8981
      initContainers:
      - name: volume-init
        image: public.ecr.aws/docker/library/busybox:1.36.1-uclibc
        command:
        - sh
        - -c
        - mkdir -m 0700 -p /storage-cas/persistent_state /storage-ac/persistent_state
        volumeMounts:
        - mountPath: /storage-cas
          name: cas
        - mountPath: /storage-ac
          name: ac
      volumes:
      - name: configs
        projected:
          sources:
          - configMap:
              name: storage
              items:
              - key: storage.jsonnet
                path: storage.jsonnet
          - configMap:
              name: common
              items:
              - key: common.libsonnet
                path: common.libsonnet
  volumeClaimTemplates:
  - metadata:
      name: cas
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 70Gi
  - metadata:
      name: ac
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "80"
    prometheus.io/scrape: "true"
  name: storage
  namespace: buildbarn
spec:
  clusterIP: None
  ports:
  - port: 8981
    protocol: TCP
    name: grpc
  selector:
    app: storage
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storage
  namespace: buildbarn
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: storage
